language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
install:
  - make dependencies
script:
  - make lint
  - make test
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
